[package]
edition = "2021"
name = "marimari-api"
version = "0.1.0"

[dependencies]
axum = "0.5"
mime = "0.3"
serde_json = "1.0"
tracing = "0.1"
url = "2.2.2"

domain = { path = "../domain" }
usecase = { path = "../usecase" }
dynamodb_repository = { path = "../infra/dynamodb_repository"}
context = { path = "../context" }

[dependencies.hyper]
features = ["full"]
version = "0.14"

[dependencies.lambda-web]
features = ["hyper"]
version = "0.2.0"

[dependencies.tokio]
features = ["full"]
version = "1.21.1"

[dependencies.tower]
features = ["full"]
version = "0.4"

[dependencies.tower-http]
features = ["trace"]
version = "0.3.0"

[dependencies.tracing-subscriber]
features = ["env-filter"]
version = "0.3"

[dev-dependencies]
axum-test-helper = "0.1.1"