name: CI

on: [push]

jobs:
  test:
    name: API Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
  deploy:
    name: Deploy API to AWS Lambda
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
    - name: Build API
      run: |
        cargo install cross 
        cross build --release --target x86_64-unknown-linux-musl
    - name: Zip archive
      run: |
        cp target/x86_64-unknown-linux-musl/release/marimari-api ./bootstrap
        zip lambda.zip bootstrap
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::553685767236:role/lambda
        aws-region: ap-northeast-1
    - name: Deploy ZIP file to AWS Lambda
      run: |
        aws lambda create-function --function-name marimari-api \
          --handler bootstrap \
          --zip-file fileb://./target/lambda/basic/bootstrap.zip \
          --runtime provided.al2 \ 
          --role role-to-assume \
          --environment Variables={RUST_BACKTRACE=1} \
          --tracing-config Mode=Active
