name: CI

on: [push]

jobs:
  test:
    name: API Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
  deploy:
    name: Deploy API to AWS Lambda
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9.0'
        architecture: 'x64'
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::553685767236:role/lambda
        aws-region: ap-northeast-1
    - run: pip install ziglang
    - run: cargo install cargo-zigbuild
    - run: cargo install cargo-lambda
    - run: cargo lambda build
    - run: cargo lambda deploy --enable-function-url marimari-admin-api
